# Generated by Django 3.2.6 on 2022-02-23 13:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protofolioapp', '0002_auto_20220203_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
