# Generated by Django 3.2.6 on 2022-02-25 07:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protofolioapp', '0003_auto_20220223_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='projects'),
        ),
    ]
